name: Run Headless Tests on Windows Server

on:
  push:
    branches: [ "feature/testing" ]
  pull_request:
    branches: [ "feature/testing" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B test -Pwindows -Pci-build -Dno-native-profile -X -e
      - name: Describe current commit
        run: echo "commit_sha=$("${{ github.sha }}".SubString(0,7))" >> $env:GITHUB_ENV
      - name: Remove Previous Build Artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.issue;
            (await github.rest.actions.listArtifactsForRepo({ owner, repo })).data.artifacts
              .filter(({ name }) => (name.startsWith('pdf-over-${{ github.event.pull_request.number || github.ref_name }}-') && name.endsWith('windows-x86_64')))
              .forEach(({ id, name }) => { console.log('Deleting '+name+' ('+id+')'); github.rest.actions.deleteArtifact({ owner, repo, artifact_id: id }); });
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf-over-${{ github.event.pull_request.number || github.ref_name }}-${{ env.commit_sha }}-windows-x86_64
          path: pdf-over-build

      - name: Install VcXsrv
        run: |
          # Download and install VcXsrv
          Invoke-WebRequest -Uri "https://sourceforge.net/projects/vcxsrv/files/latest/download" -OutFile "vcxsrv.exe"
          Start-Process -FilePath "vcxsrv.exe" -ArgumentList ":0 -ac -screen 0 1024x768x24" -NoNewWindow -Wait

      - name: Set DISPLAY environment variable
        run: echo "DISPLAY=localhost:0" >> $GITHUB_ENV

permissions:
    contents: read
    actions: write
