name: Build MacOS (x86_64)
on:
  push:
    branches: [ "feature/simple-ui-test" ]
  pull_request:
    branches: [ "feature/simple-ui-test" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DargLine="-XstartOnFirstThread"
      - name: Run tests
        run: mvn test -DargLine="-XstartOnFirstThread"
      - name: Describe current commit
        run: echo "commit_sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Remove Previous Build Artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.issue;
            (await github.rest.actions.listArtifactsForRepo({ owner, repo })).data.artifacts
              .filter(({ name }) => (name.startsWith('pdf-over-${{ github.event.pull_request.number || github.ref_name }}-') && name.endsWith('macos-x86_64')))
              .forEach(({ id, name }) => { console.log('Deleting '+name+' ('+id+')'); github.rest.actions.deleteArtifact({ owner, repo, artifact_id: id }); });
      - name: Check pdf-over-build directory
        run: |
          echo "Listing contents of pdf-over-build directory:"
          ls -la pdf-over-build

      - name: Make scripts executable
        run: |
          if [ -d "pdf-over-build" ]; then
            chmod +x pdf-over-build/*.sh pdf-over-build/jre/bin/*
          else
            echo "Directory pdf-over-build does not exist."
          fi
      - name: Tar bundle
        run: tar -C pdf-over-build -cvf pdf-over.tar ./
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf-over-${{ github.event.pull_request.number || github.ref_name }}-${{ env.commit_sha }}-macos-x86_64
          path: pdf-over.tar

permissions:
    contents: read
    actions: write
