name: Build Linux
on:
  push:
    branches: [ "feature/testing" ]
  pull_request:
    branches: [ "feature/testing" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y x11-apps xauth openjdk-17-jdk maven xvfb libgtk-3-0 && sudo rm -rf /var/lib/apt/lists/*
      - name: Build with Maven
        run: xvfb-run mvn -B clean install -Plinux -Pci-build -Dno-native-profile
      - name: Describe current commit
        run: echo "commit_sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Remove Previous Build Artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.issue;
            (await github.rest.actions.listArtifactsForRepo({ owner, repo })).data.artifacts
              .filter(({ name }) => (name.startsWith('pdf-over-${{ github.event.pull_request.number || github.ref_name }}-') && name.endsWith('linux-x86_64')))
              .forEach(({ id, name }) => { console.log('Deleting '+name+' ('+id+')'); github.rest.actions.deleteArtifact({ owner, repo, artifact_id: id }); });
      - name: Set executable permissions
        run: chmod +x pdf-over-build/*.sh pdf-over-build/jre/bin/*
      - name: Tar bundle
        run: tar -C pdf-over-build -cvf pdf-over.tar ./
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf-over-${{ github.event.pull_request.number || github.ref_name }}-${{ env.commit_sha }}-linux-x86_64
          path: pdf-over.tar

permissions:
    contents: read
    actions: write
